### ISSUE TITLE
ActionView::Template::Error (unknown keyword: permitted_classes):

### ISSUE THREAD

**Issue by 85636682** [rails-engine/role_core#12]
修改保存了角色的权限后，在进入修改页面报错，结果如下：
用户和角色是has_many to has_many
用了cancancan
```
ActionView::Template::Error (unknown keyword: permitted_classes):
    23:         </div>
    24:       </div>
    25:       <div class="col-md-12">
    26:         <%= render partial: "permissions", locals: {f: f, name: :permissions_attributes, permissions: role.permissions} %>
    27:       </div>
    28:     </div>
    29:   </div>
```

**Comment by jasl** [comment]
收到，我稍等看下，是最新版本触发的么？还是你有用一阵突然不行的

**Comment by jasl** [comment]
这个 参数是 `YAML.safe_load` 的，你方便的话可以试试升级 `options_model` 到 0.0.16 版 或者看下你现在依赖的是版本号是多少么（从 `Gemfile.lock`）来看

**Comment by 85636682** [comment]
```
options_model (0.0.16)
      activemodel (>= 5, < 7)
      activesupport (>= 5, < 7)
```
已经是0.0.16了

**Comment by 85636682** [comment]
```
options_model (0.0.16)
      activemodel (>= 5, < 7)
      activesupport (>= 5, < 7)
```
```
role_core (0.0.25)
      options_model (>= 0.0.12, < 1.0)
      rails (>= 5, < 7)
```
```
options_model (~> 0.0.16)
```
本来是0.0.16，也尝试了添加了这个gem，但是还是一样的报错

**Comment by jasl** [comment]
明白了，我按照我的文档构建个环境测试一下

**Comment by jasl** [comment]
@85636682 还是需要你给一个完整的错误信息。。。我没复现出来

**Comment by 85636682** [comment]
```
Processing by Admin::RolesController#edit as HTML
  Parameters: {"id"=>"1"}
  Admin Load (0.6ms)  SELECT  `admins`.* FROM `admins` WHERE `admins`.`id` = 1 LIMIT 1
  ↳ app/controllers/admin_controller.rb:16
  Role Load (0.6ms)  SELECT  `roles`.* FROM `roles` WHERE `roles`.`type` IN ('Role') AND `roles`.`id` = 1 LIMIT 1
  ↳ app/controllers/admin/roles_controller.rb:48
  Rendering admin/roles/edit.html.erb within layouts/admin
  Rendered admin/roles/_form.html.erb (5.4ms)
  Rendered admin/roles/edit.html.erb within layouts/admin (8.7ms)
Completed 500 Internal Server Error in 31ms (ActiveRecord: 6.8ms)



ActionView::Template::Error (unknown keyword: permitted_classes):
    23:         </div>
    24:       </div>
    25:       <div class="col-md-12">
    26:         <%= render partial: "permissions", locals: {f: f, name: :permissions_attributes, permissions: role.permissions} %>
    27:       </div>
    28:     </div>
    29:   </div>

app/views/admin/roles/_form.html.erb:26:in `block in _app_views_admin_roles__form_html_erb___4292200800806999415_70312410266380'
app/views/admin/roles/_form.html.erb:1:in `_app_views_admin_roles__form_html_erb___4292200800806999415_70312410266380'
app/views/admin/roles/edit.html.erb:3:in `_app_views_admin_roles_edit_html_erb__374249906488964348_70312410296820'
```

**Comment by 85636682** [comment]
这是我更新时候，后台的运行情况
```
Started PATCH "/admin/roles/1" for 127.0.0.1 at 2019-08-07 17:25:19 +0800
   (0.4ms)  SET NAMES utf8mb4,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
  ↳ /Users/stephen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/webpacker-2b5267335c69/lib/webpacker/dev_server_proxy.rb:29
Processing by Admin::RolesController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"4tEznIivxHaPq6g86FzMhRaGJJSaGyWZwnh+kDv3Np5uOfcLgRWBaZfzrO5p+nKxkrOKiwS1V/cHRFa9u7zSBQ==", "role"=>{"name"=>"财务", "permissions_attributes"=>{"spu"=>{"create"=>"1", "destroy"=>"0", "update"=>"0", "read"=>"1", "read_public"=>"0", "sku"=>{"create"=>"1", "destroy"=>"0", "update"=>"0"}}, "user"=>{"create"=>"1", "destroy"=>"0", "update"=>"0", "read"=>"1", "read_public"=>"0"}}}, "commit"=>"保 存", "id"=>"1"}
  Admin Load (0.6ms)  SELECT  `admins`.* FROM `admins` WHERE `admins`.`id` = 1 LIMIT 1
  ↳ app/controllers/admin_controller.rb:16
  Role Load (1.0ms)  SELECT  `roles`.* FROM `roles` WHERE `roles`.`type` IN ('Role') AND `roles`.`id` = 1 LIMIT 1
  ↳ app/controllers/admin/roles_controller.rb:48
   (0.2ms)  BEGIN
  ↳ app/controllers/admin/roles_controller.rb:31
  Role Update (28.0ms)  UPDATE `roles` SET `permissions` = '---\n:spu:\n  :create: true\n  :destroy: false\n  :update: false\n  :read: true\n  :read_public: false\n  :sku:\n    :create: true\n    :destroy: false\n    :update: false\n:user:\n  :create: true\n  :destroy: false\n  :update: false\n  :read: true\n  :read_public: false\n', `updated_at` = '2019-08-07 17:25:19' WHERE `roles`.`id` = 1
  ↳ app/controllers/admin/roles_controller.rb:31
   (1.0ms)  COMMIT
  ↳ app/controllers/admin/roles_controller.rb:31
Redirected to http://localhost:3000/admin/roles
Completed 302 Found in 59ms (ActiveRecord: 41.0ms)
```

**Comment by jasl** [comment]
> 这是后台完整的报错处执行情况
> 
> ```
> Processing by Admin::RolesController#edit as HTML
>   Parameters: {"id"=>"1"}
>   Admin Load (0.6ms)  SELECT  `admins`.* FROM `admins` WHERE `admins`.`id` = 1 LIMIT 1
>   ↳ app/controllers/admin_controller.rb:16
>   Role Load (0.6ms)  SELECT  `roles`.* FROM `roles` WHERE `roles`.`type` IN ('Role') AND `roles`.`id` = 1 LIMIT 1
>   ↳ app/controllers/admin/roles_controller.rb:48
>   Rendering admin/roles/edit.html.erb within layouts/admin
>   Rendered admin/roles/_form.html.erb (5.4ms)
>   Rendered admin/roles/edit.html.erb within layouts/admin (8.7ms)
> Completed 500 Internal Server Error in 31ms (ActiveRecord: 6.8ms)
> 
> 
> 
> ActionView::Template::Error (unknown keyword: permitted_classes):
>     23:         </div>
>     24:       </div>
>     25:       <div class="col-md-12">
>     26:         <%= render partial: "permissions", locals: {f: f, name: :permissions_attributes, permissions: role.permissions} %>
>     27:       </div>
>     28:     </div>
>     29:   </div>
> 
> app/views/admin/roles/_form.html.erb:26:in `block in _app_views_admin_roles__form_html_erb___4292200800806999415_70312410266380'
> app/views/admin/roles/_form.html.erb:1:in `_app_views_admin_roles__form_html_erb___4292200800806999415_70312410266380'
> app/views/admin/roles/edit.html.erb:3:in `_app_views_admin_roles_edit_html_erb__374249906488964348_70312410296820'
> ```

这个没贴全吧？我是想看异常堆栈了解下是哪里调用的那个函数，这个应该是反序列化时候会调用的

**Comment by jasl** [comment]
更新看上去没问题，也就是序列化是对的

**Comment by 85636682** [comment]
> > 这是后台完整的报错处执行情况
> > ```
> > Processing by Admin::RolesController#edit as HTML
> >   Parameters: {"id"=>"1"}
> >   Admin Load (0.6ms)  SELECT  `admins`.* FROM `admins` WHERE `admins`.`id` = 1 LIMIT 1
> >   ↳ app/controllers/admin_controller.rb:16
> >   Role Load (0.6ms)  SELECT  `roles`.* FROM `roles` WHERE `roles`.`type` IN ('Role') AND `roles`.`id` = 1 LIMIT 1
> >   ↳ app/controllers/admin/roles_controller.rb:48
> >   Rendering admin/roles/edit.html.erb within layouts/admin
> >   Rendered admin/roles/_form.html.erb (5.4ms)
> >   Rendered admin/roles/edit.html.erb within layouts/admin (8.7ms)
> > Completed 500 Internal Server Error in 31ms (ActiveRecord: 6.8ms)
> > 
> > 
> > 
> > ActionView::Template::Error (unknown keyword: permitted_classes):
> >     23:         </div>
> >     24:       </div>
> >     25:       <div class="col-md-12">
> >     26:         <%= render partial: "permissions", locals: {f: f, name: :permissions_attributes, permissions: role.permissions} %>
> >     27:       </div>
> >     28:     </div>
> >     29:   </div>
> > 
> > app/views/admin/roles/_form.html.erb:26:in `block in _app_views_admin_roles__form_html_erb___4292200800806999415_70312410266380'
> > app/views/admin/roles/_form.html.erb:1:in `_app_views_admin_roles__form_html_erb___4292200800806999415_70312410266380'
> > app/views/admin/roles/edit.html.erb:3:in `_app_views_admin_roles_edit_html_erb__374249906488964348_70312410296820'
> > ```
> 
> 这个没贴全吧？我是想看异常堆栈了解下是哪里调用的那个函数，这个应该是反序列化时候会调用的

![image](https://user-images.githubusercontent.com/1079461/62688795-27ac2100-b9fc-11e9-91ca-bbdfd2466d22.png)

**Comment by jasl** [comment]
额 Ruby 2.5.1 是吧，我看看是不是跟 Ruby 版本有关。。。

**Comment by 85636682** [comment]
是的，忘记放ruby版本了
```
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
```

**Comment by jasl** [comment]
抱歉耽误你工作了，我再看看，对了，你用我这项目的 Demo 会遇到问题么？还是你按照我文档的方式操作，出现问题了

**Comment by 85636682** [comment]
谢谢你提供这个gem才真。我是按照你的文档，也参考了你的demo，配置到自己的系统，出现问题

**Comment by jasl** [comment]
好的，方便的话，测试一下直接用我的 Demo 有啥问题吧，我需要晚上写一个你这个场景的测试项目来，如果有问题 我就来修掉，没有可以看看能否直接拿去用~

**Comment by jasl** [comment]
@85636682 知道原因了，原因在于 Ruby 2.5.1 自带的 YAML 的序列化库 `psych` 版本过低，所以你只需要在你 `Gemfile` 里加上 `gem "psych"` 要求使用新版就可以了

**Comment by jasl** [comment]
<https://github.com/jasl/role_core_demo> 写了个 demo （其实就是把这 Gem 内的 dummy app 抽成了独立应用

**Comment by 85636682** [comment]
谢谢，按你的问题已经解决，或者把ruby升级到2.6.2
