### ISSUE TITLE
结合cancancan后skip_authorization_check方法失效

### ISSUE THREAD

**Issue by clousky2020** [rails-engine/role_core#17]
在一个controller中，有部分是为页面的autocomplete插件准备的，比如下面这个搜索返回供应商名称：
```
  #cancancan定义
  load_and_authorize_resource
  skip_authorization_check :only => :check_purchase_supplier

 def check_purchase_supplier
    @purchase_supplier = PurchaseSupplier.search_name(params[:term]).map(&:name)
    render json: @purchase_supplier
  end
```
在使用了role_core后，后台页面接收到JSON，但被截断了，302跳转：
```
Started GET "/expense/get_expense_type?term=+" for ::1 at 2020-11-04 21:48:40 +0800
Processing by ExpenseController#get_expense_type as JSON
  Parameters: {"term"=>"浙江"}
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/helpers/session_helper.rb:8:in `current_user'
  Role Load (0.5ms)  SELECT "roles".* FROM "roles" INNER JOIN "role_assignments" ON "roles"."id" = "role_assignments"."role_id" WHERE "roles"."type" = $1 AND "role_assignments"."user_id" = $2  [["type", "Role"], ["user_id", 1]]
  ↳ app/models/user.rb:24:in `map'
Redirected to http://localhost:3000/
Completed 302 Found in 26ms (ActiveRecord: 0.7ms | Allocations: 14019)
```
目前发现把这个`check_purchase_supplier`加入`config/initializers/role_core.rb`再赋予role能通过验证，但类似的controller有很多，这种通用的内容不应该重复多处设定。
不知道是否已经有别的解决方法但我没有发现？

**Comment by jasl** [comment]
抱歉刚才在休息，从你的情况看，你希望在控制器里禁用某些 RoleCore 里定义的权限的检查？

我的理解你的需求是：你需要知道或者能够自定义某个权限在 cancancan 上的名称，以便在控制器里需要跳过检查时指定

**Comment by jasl** [comment]
我重新看了一下问题似乎懂了，`skip_authorization_check` 这个会检查 `can :check_purchase_supplier, 当前模型` 然而你这里的`:check_purchase_supplier` 权限应该是要作用于很多模型的，对吧？

**Comment by jasl** [comment]
我应该考虑到这种情况了，可以试试

`permission :check_purchase_supplier, action: :check_purchase_supplier, subject: :all`

注：如果 `action` 和 权限名 一致的话，`action` 可以省略

我在 dummy 里增加了一个[演示](https://github.com/rails-engine/role_core/blob/master/test/dummy/config/initializers/role_core.rb#L32)，增加一个超级管理员权限 

`permission :super, action: :manage, subject: :all`

这个权限等价于 cancancan 的 `can :manage, :all`

**Comment by clousky2020** [comment]
就像您最开始想的那样，controller中有一些public method，类似上面的`def check_purchase_supplier `，任何人都能访问方法得到结果。而当我没有将其添加进`role_core.rb`内时，不应该被检查权限，但结果是当我调用时，提示我没有权限进行此操作。最开始我以为是cancancan对该controller下的所有method进行check，所以我添加了`skip_authorization_check :only => :check_purchase_supplier`，但并没有作用。
确实像您想的那样，该public method可能会有多个不同的地方去调用。我不想每写一个新的public method，又要到`role_core.rb`里去添加，然后再更新一下所有的role使其具有该权限。

**Comment by jasl** [comment]
> 我应该考虑到这种情况了，在 dummy 里增加了一个超级管理员权限的演示
> 
> `permission :super, action: :manage, subject: :all`
> 
> 这个写法等价于 cancancan 的 `can :manage, :all`
> 
> 对于你的情况，我觉得可以试试这样：
> 
> `permission :check_purchase_supplier, action: :check_purchase_supplier, subject: :all`
> 
> 注1：如果 `action` 和 权限名 一致的话，`action` 可以省略
> 注2：如果这个权限对应的是几个模型，参考 cancancan 的文档可以这样去写 `subject: [User, Supplier]`

@clousky2020 你看看这个对你有没有帮助

**Comment by jasl** [comment]
> 就像您最开始想的那样，controller中有一些public method，类似上面的`def check_purchase_supplier `，任何人都能访问方法得到结果。而当我没有将其添加进`role_core.rb`内时，不应该被检查权限，但结果是当我调用时，提示我没有权限进行此操作。最开始我以为是cancancan对该controller下的所有method进行check，所以我添加了`skip_authorization_check :only => :check_purchase_supplier`，但并没有作用。
> 确实像您想的那样，该public method可能会有多个不同的地方去调用。我不想每写一个新的public method，又要到`role_core.rb`里去添加，然后再更新一下所有的role使其具有该权限。

懂了，这种全局的默认权限我觉得直接在 cancancan 上定义就好了，绕过 RoleCore，我觉得你的 `cancancan` 的 `ability.rb` 可能是会是这样

```ruby
class Ability
  include CanCan::Ability

  def initialize(user)
    # 先应用 RoleCore 的权限定义
    user.computed_permissions.call(self, user)

    # 定义不通过 RoleCore 管理的权限
    can :check_purchase_supplier, :all
  end
end
```

**Comment by clousky2020** [comment]
虽然有看过cancancan的后面的设定会覆盖前面的规则，但并没有想到能用此完成目的。十分感谢您的教导！
