### ISSUE TITLE
clone下代码后，bundle install提示mimemagic版本过低

### ISSUE THREAD

**Issue by liijunwei** [rails-engine/role_core#23]
需要`bundle update mimemagic`
![image](https://user-images.githubusercontent.com/48843657/147389011-c95e5dc5-8f74-4233-9147-6bfadb24ae90.png)

**Comment by jasl** [comment]
稍等我我搞一波

**Comment by jasl** [comment]
应该没问题了，顺带兼容 Rails 7 了
