### ISSUE TITLE
Unknown alias:  Psych::BadAlias

### ISSUE THREAD

**Issue by xgrei** [rails-engine/role_core#28]
报告一个问题: 

[7f8f88025d6e5a6dc34e5fa8c1ff7ef24e2ef4b7](https://github.com/rails-engine/role_core/commit/7f8f88025d6e5a6dc34e5fa8c1ff7ef24e2ef4b7) 

此版本引入的psych `4.0.3` 会引起`visit_Psych_Nodes_Alias': Unknown alias: redis (Psych::BadAlias)` 错误。
此错误无法正常解析yaml中的alias

只要yaml文件中有如下语法，就会报这个错误:

```yaml
redis: &redis
  redis_host: 127.0.0.1
  redis_port: 6379

development:
  <<: *redis

staging:
  <<: *redis
```

ruby: `2.7.5`
rails: `6.1.4`

目前的解决办法是在gemfile中这样引入: 

```ruby
gem "role_core", github: "rails-engine/role_core", ref: "8578d64"
gem "psych", "~> 3.3.2"
```

**Comment by jasl** [comment]
你可以帮看下 没有上你的解决办法的时候，你的工程使用的 psych 版本么？

**Comment by xgrei** [comment]
> 你可以帮看下 没有上你的解决办法的时候，你的工程使用的 psych 版本么？

是最新的 `4.0.3`

**Comment by jasl** [comment]
> > 你可以帮看下 没有上你的解决办法的时候，你的工程使用的 psych 版本么？
> 
> 是最新的 `4.0.3`

你试试单独加 `gem "psych", "~> 3.3.2"` 这一句能解决问题么？

**Comment by xgrei** [comment]
> 

也没问题

- 只要加了 `role_core`，就会在`gemfile.lock`文件中引入psych `4.0.3`，就会出错，所以要单独加一行`gem "psych", "~> 3.3.2"`
- 两行都不加，也没问题

**Comment by jasl** [comment]
> > 
> 
> 也没问题
> 
> * 只要加了 `role_core`，就会在`gemfile.lock`文件中引入psych `4.0.3`，就会出错，所以要多加一行`gem "psych", "~> 3.3.2"`
> * 加一行 `gem "psych", "~> 3.3.2"` 没问题
> * 两行都不加，也没问题

我看了一下，RoleCore 是没有指定 `psych` 依赖的，而且 gem 的 Gemfile.lock 不影响项目，不知道是什么依赖导致你项目里的被升级上去了。

就用 `gem "psych", "~> 3.3.2"` 来解决吧

**Comment by xgrei** [comment]
> > > 
> > 
> > 
> > 也没问题
> > 
> > * 只要加了 `role_core`，就会在`gemfile.lock`文件中引入psych `4.0.3`，就会出错，所以要多加一行`gem "psych", "~> 3.3.2"`
> > * 加一行 `gem "psych", "~> 3.3.2"` 没问题
> > * 两行都不加，也没问题
> 
> 我看了一下，RoleCore 是没有指定 `psych` 依赖的，而且 gem 的 Gemfile.lock 不影响项目，不知道是什么依赖导致你项目里的被升级上去了。
> 
> 就用 `gem "psych", "~> 3.3.2"` 来解决吧

你好，我尝试用`ruby2.7.5 + rails6.1.4`这个组合新建一个项目，然后在Gemfile中加入`gem "role_core", "~> 0.0.27"`。

然后对比 `Gemfile.lock`，确实引入了`psych 4.0.3`，移除 `role_core`后，`psych 4.0.3`就消失了。

**Comment by jasl** [comment]
> > > > 
> > > 
> > > 
> > > 也没问题
> > > 
> > > * 只要加了 `role_core`，就会在`gemfile.lock`文件中引入psych `4.0.3`，就会出错，所以要多加一行`gem "psych", "~> 3.3.2"`
> > > * 加一行 `gem "psych", "~> 3.3.2"` 没问题
> > > * 两行都不加，也没问题
> > 
> > 
> > 我看了一下，RoleCore 是没有指定 `psych` 依赖的，而且 gem 的 Gemfile.lock 不影响项目，不知道是什么依赖导致你项目里的被升级上去了。
> > 就用 `gem "psych", "~> 3.3.2"` 来解决吧
> 
> 你好，我尝试用`ruby2.7.5 + rails6.1.4`这个组合新建一个项目，然后在Gemfile中加入`gem "role_core", "~> 0.0.27"`。
> 
> 然后对比 `Gemfile.lock`，确实引入了`psych 4.0.3`，移除 `role_core`后，`psych 4.0.3`就消失了。
> 
> 但正如你所说，应该是和项目里的其他gem产生冲突了，在新项目里的yaml文件中的alias语法没有出现问题。

psych 4 默认是不允许 alias 的，所以会报这个错。

我来研究一下，不知道是因为什么引入新版本的 我给的约束是 `>= 3.2` 或许跟这个有关（这样才能兼容 Rails 6 和 7），如果 Rails 6.1 的默认 psych 低于 3.2 那么可能会直接去拿最新的版本，然后因为兼容问题（我不确定 psych 4 的兼容有没有backport到 6.1）导致问题

你要方便的话，再帮我看看没引入 role_core 时候，新建的项目的 psych 版本？我觉得是我的这个推测

**Comment by xgrei** [comment]
> 

看来还是有问题，我在项目的`credentials`文件中加入如下内容:

```
redis: &redis
  redis_host: 127.0.0.1
  redis_port: 6379

development:
  <<: *redis

staging:
  <<: *redis
```

然后在 `config/initializers/application_controller_renderer.rb` 文件中试图调用 `Rails.application.credentials[:development][:redis_host]` 时，就会报如下错误: 

```
ruby/2.7.5/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:430:in `visit_Psych_Nodes_Alias': Unknown alias: redis (Psych::BadAlias)
	from /Users/someguy/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/visitor.rb:30:in `visit'
	from /Users/someguy/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/visitor.rb:6:in `accept'
	from /Users/someguy/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:35:in `accept'
	from /Users/someguy/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
	from /Users/someguy/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:343:in `each'
	from /Users/someguy/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:343:in `each_slice'
	from /Users/someguy/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:343:in `revive_hash'
	from /Users/someguy/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
	from /Users/someguy/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/visitor.rb:30:in `visit'
	from /Users/someguy/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/visitor.rb:6:in `accept'
	from /Users/someguy/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:35:in `accept'
	from /Users/someguy/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
	from /Users/someguy/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:343:in `each'
	from /Users/someguy/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:343:in `each_slice'
	from /Users/someguy/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:343:in `revive_hash'
	from /Users/someguy/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
	from /Users/someguy/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/visitor.rb:30:in `visit'
	from /Users/someguy/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/visitor.rb:6:in `accept'
	from /Users/someguy/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:35:in `accept'
	from /Users/someguy/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
	from /Users/someguy/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/visitor.rb:30:in `visit'
	from /Users/someguy/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/visitor.rb:6:in `accept'
	from /Users/someguy/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:35:in `accept'
	from /Users/someguy/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych.rb:335:in `safe_load'
	from /Users/someguy/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych.rb:370:in `load'
	from /Users/someguy/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-6.1.5/lib/active_support/encrypted_configuration.rb:42:in `deserialize'
	from /Users/someguy/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-6.1.5/lib/active_support/encrypted_configuration.rb:33:in `config'
	from /Users/someguy/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-6.1.5/lib/active_support/encrypted_configuration.rb:11:in `[]'
	from /Users/someguy/workspace/ruby/testpsych/config/initializers/application_controller_renderer.rb:10:in `<main>'
```

**Comment by jasl** [comment]
你不装role_core先，看看 psych 的版本是啥？

我的推测是 “我给的约束是 >= 3.2 或许跟这个有关（这样才能兼容 Rails 6 和 7），如果 Rails 6.1 的默认 psych 低于 3.2 那么可能会直接去拿最新的版本，然后因为兼容问题（我不确定 psych 4 的兼容有没有backport到 6.1）导致问题”

**Comment by xgrei** [comment]
> 你不装role_core先，看看 psych 的版本是啥？看起来 6.1.4 并没有兼容 psych 4，4 默认禁止 alias 的
> 
> 我的推测是 “我给的约束是 >= 3.2 或许跟这个有关（这样才能兼容 Rails 6 和 7），如果 Rails 6.1 的默认 psych 低于 3.2 那么可能会直接去拿最新的版本，然后因为兼容问题（我不确定 psych 4 的兼容有没有backport到 6.1）导致问题”

不装`role_core`的话，`Gemfile.lock`中没有`psych`

**Comment by jasl** [comment]
hmmm，那就是用自带的了（这个是std gem），那还是先在 gemfile 里指定 psych 版本吧
我回头看看2.6的自带版本是多少 > 3.2 我也就不写这个版本约束了

**Comment by xgrei** [comment]
> 

好的，谢谢
