### ISSUE TITLE
Updated Permission through raw sql query does not reflect in role object returned in active record

### ISSUE THREAD

**Issue by swapnilb-cuelogic** [rails-engine/role_core#4]
I am facing an issue with updating permissions through raw sql query, as the data in database gets updated but not reflected through active record

*Steps to produce
  1. Create role

INSERT INTO roles
        (name, type, created_at, updated_at)
    VALUES ('Test1', 'Role', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

   * Permisions are getting created, as mentioned in role_core initializer

  2. Update permissions

    UPDATE roles
      SET permissions='{"users": {"manage": false}', updated_at = CURRENT_TIMESTAMP
    WHERE id = 1;

  3. This gets update in database but not accessible through active record

  4  role = Role.last in rails console
    #<Role id: 4, name: "Test1", permissions: #<Global:OptionsModel {:users=>{:manage=>true} >, type: "Role", created_at: "2018-06-22 20:24:56", updated_at: "2018-06-22 20:25:22">

**Comment by jasl** [comment]
Hi!
RoleCore is not friendly with raw SQL query because it's using ActiveRecord's [`serialize`](http://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/Serialization/ClassMethods.html) which means: permissions would be serialized by YAML coder and then persisted into a `text` column, and this is the AR‘s default behavior (I think it's for compatibility), so query them is difficulty.

So your inserting SQL is wrong, you can try the dummy and see the right data in database.

Fortunately the serialize coder could be changed, so if you're using newer version of MySQL or PG, you may want to use `json` or `hstore` column type that queryable.

But, for now I don't given a easy way to change the coder, so you may need to override [`dump` & `load`](https://github.com/jasl-lab/options_model/blob/master/lib/options_model/concerns/serialization.rb#L23-L46) by your self for `PermissionSet` class.

**Comment by jasl** [comment]
Oh, I don't know about MySQL's `json`, for PG, you can keep using `text` (the default way) or `json` or `jsonb`, `hstore` isn't work because it's not support nested structure.

If you still want to using Json in `text` (like your insert SQL do), rewriting serialize coder also works

**Comment by swapnilb-cuelogic** [comment]
Hi @jasl  ,
We have some restrictions in our process due to which we cannot avoid updating database without running raw sql queries.
We are still exploring other options which goes with what we want or else we might even add custom solution for time being.

**Comment by jasl** [comment]
Updating database through raw SQL is OK, but you need to transform the Json to YAML format, RoleCore using YAML to serialize data as ActiveRecord default behavior.

For example, your Json `{"users": {"manage": false}}` in YAML is `---\n:users:\n  :manage: false\n`

**Comment by renzodiaz** [comment]
@jasl Hi I was looking a gem that provides these granularity roles and I found this gem after days of research,  trying to use this in my project but when trying to create a role through rails console `Role.create(name: "Viewer", permissions: {team: {read: true}}.to_yaml)` I'm getting this error `can't dump: was supposed to be a #<Class:0x00007fe1e6e6a1e8>, but was a String. -- "---\n:team:\n  :read: true\n"`, I would appreciate if you can tell me how can I create roles please.

**Comment by jasl** [comment]
> @jasl Hi I was looking a gem that provides these granularity roles and I found this gem after days of research, trying to use this in my project but when trying to create a role through rails console `Role.create(name: "Viewer", permissions: {team: {read: true}}.to_yaml)` I'm getting this error `can't dump: was supposed to be a #<Class:0x00007fe1e6e6a1e8>, but was a String. -- "---\n:team:\n :read: true\n"`, I would appreciate if you can tell me how can I create roles please.

Use like this

```
Role.new name: "Test", permissions_attributes: { foo: true, project: { create: true, read: true } }
 => #<Role id: nil, name: "Test", permissions: #<Global:OptionsModel {:foo=>true, :bar=>false, :project=>{:create=>true, :destroy=>false, :update=>false, :read=>true, :read_public=>false, :task=>{:create=>true, :destroy=>false, :update=>false, :update_my_own=>true, :destroy_my_own=>true}}, :task=>{:read=>false, :create=>true, :destroy=>false, :update=>false}}>, type: "Role", created_at: nil, updated_at: nil>
```

**Comment by renzodiaz** [comment]
it works, thank you so much!

**Comment by jasl** [comment]
I have added dynamic permission example to dummy app, so I'm close this issue, for any question please create a new issue
