### ISSUE TITLE
DEPRECATION WARNING

### ISSUE THREAD

**Issue by csxiaodiao** [rails-engine/role_core#42]
DEPRECATION WARNING: Passing the coder as positional argument is deprecated and will be removed in Rails 7.2.
Please pass the coder as a keyword argument:
serialize :permissions, coder: #<Class:0x00007f9662d92ec0>

**Comment by jasl** [comment]
Thank you for the report!
I'll fix this week.

**Comment by jasl** [comment]
Fixed, and released v0.0.29
