### ISSUE TITLE
使用block和accessible_by获取列表时，会报错

### ISSUE THREAD

**Issue by nyrf** [rails-engine/role_core#44]
如果使用这种形式的block，然后获取自己发布的项目时，会出现
```
The accessible_by call cannot be used with a block 'can' definition.The SQL cannot be determined for :index Project
```

```ruby
@projects = Project.accessible_by(current_ability)
```

```ruby
 permission :read_own, action: :read  do |user, project|
      user.id = project.user_id
  end
```

看cancan的wiki好像要用这种方式才行

```ruby
 permission :read_own, action: :read, user_id: user.id
```

但在role_core.rb中，好像无法传递user

**Comment by nyrf** [comment]
> `@projects = Project.accessible_by(current_ability)` 这个是最近的cancancan加的做法吗？之前没注意过有这个用法

好像以前就有的https://github.com/CanCanCommunity/cancancan/blob/develop/docs/fetching_records.md 这个方法好像只能接受hash conditions

**Comment by jasl** [comment]
如果只接受 hash 的话 我感觉还是可以做的
只要把权限定义翻译到cancancan的ability的时候不用 block 就好了

我看我之前就支持了
https://github.com/rails-engine/role_core/blob/master/lib/role_core/contrib/can_can_can_permission.rb#L22-L26

不过咋弄我得回忆一下，你要不要先研究一波？

**Comment by nyrf** [comment]
> 如果只接受 hash 的话 我感觉还是可以做的 只要把权限定义翻译到cancancan的ability的时候不用 block 就好了
> 
> 我看我之前就支持了 https://github.com/rails-engine/role_core/blob/master/lib/role_core/contrib/can_can_can_permission.rb#L22-L26
> 
> 不过咋弄我得回忆一下，你要不要先研究一波？

谢谢，我先看一下

**Comment by nyrf** [comment]
> 我翻了一下 cancancan 的文档，我大概理解了，但我不确定
> 
> 比如 dummy app 里演示的，https://github.com/rails-engine/role_core/blob/master/test/dummy/config/initializers/role_core.rb#L23-L25
> 
> ```ruby
> permission :update_my_own, action: :update, default: true do |user, task|
>   task.user_id == user.id
> end
> ```
> 
> 你要看你的业务，试试能不能避免这种使用 block，不过问题在于 `user: user`，这个我不确定你这样写 `permission :update_my_own, action: :update, default: true, user: -> { user }` 是否可行

不用block的话，就没办法传user过去，我看了下源码，role_core.rb没有办法传user，所以只能用block，`permission :update_my_own, action: :update, default: true, user: -> { user } ` 这种方式试了不行，我看换别的方法看下

**Comment by jasl** [comment]
@nyrf 试试最新的提交 https://github.com/rails-engine/role_core/commit/5f636a57832b0621b69f7a3fd805542534e0916c#diff-af3f77ec4a9c0104e6ae2e37b23db15ddd12565990edde1aa8c86196a0ca71b1

`permission :read_own, action: :read, with_user: true`

这样写

**Comment by jasl** [comment]
没问题的话我发版

**Comment by nyrf** [comment]
> 我就快速试了一下，你帮我肉测一下，没问题的话我发版

试了下，如果belongs_to不是user的话，比如是admin_user或者别的名字，这里还是会报错，这里设置自定义名称？比如我这里用的就是admin_user
https://github.com/rails-engine/role_core/commit/5f636a57832b0621b69f7a3fd805542534e0916c#diff-af3f77ec4a9c0104e6ae2e37b23db15ddd12565990edde1aa8c86196a0ca71b1R26

**Comment by nyrf** [comment]
或者不用true或者false，直接

```ruby
elsif @with_user.present?
        context.can @action, subject, @options.merge(@with_user => user)
```
用的时候也直接写成 `permission :read_own, action: :read, with_user: "admin_user"`

**Comment by jasl** [comment]
> 或者不用true或者false，直接
> 
> ```ruby
> elsif @with_user.present?
>         context.can @action, subject, @options.merge(@with_user => user)
> ```
> 
> 用的时候也直接写成 `permission :read_own, action: :read, with_user: "admin_user"`

有道理，我来改一下

另外 https://github.com/rails-engine/role_core/blob/master/lib/role_core/contrib/can_can_can_permission.rb#L19 这里 `def call(context, user, *args)` 从第二个参数开始，其实是匹配你的 `ability.rb` 的参数列表的，所以如果你如果需求特别特殊，可以把这个文件复制到你项目里，然后更新一下 `initializer` 的设置 https://github.com/rails-engine/role_core/blob/master/test/dummy/config/initializers/role_core.rb#L9

**Comment by jasl** [comment]
@nyrf 提交啦
https://github.com/rails-engine/role_core/commit/06d2374835e194eed690601a17d83b9926685b14

用 `with:` 就好
`permission :read_own, action: :read, with: :admin_user`

**Comment by nyrf** [comment]
> @nyrf 提交啦 [06d2374](https://github.com/rails-engine/role_core/commit/06d2374835e194eed690601a17d83b9926685b14)
> 
> 用 `with:` 就好 `permission :read_own, action: :read, with: :admin_user`

好的，感谢！

**Comment by nyrf** [comment]
试了下没有问题，感谢这么晚还帮忙处理问题。
