### ISSUE TITLE
What's the meaning of type column   in roles table

### ISSUE THREAD

**Issue by zll11111** [rails-engine/role_core#8]
It seems that the  "type" column in roles table  is set to 'Role' automatically. And when querying for roles, there is "roles.type in ('Role')" in the where clause. I wonder why you do it that way and how you do it. I am not able to find any clue in the repo.

**Comment by jasl** [comment]
`type` is for STI, see <https://api.rubyonrails.org/classes/ActiveRecord/Inheritance.html> 

It's not necessary, but I pre-made this to help extending, for example (I don't made this to dummy) like Redmine, there have some built-in roles that can't be modify or remove. in this case, you can create subclasses for these builtin roles such as `Anonymous`, `Owner`, `Member`, and create another class `CustomRole` for user defined roles.

I consider separate role classes would made app code clean.

**Comment by zll11111** [comment]
Thanks. I get it. I will close this issue.
